// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package opcuaclientmx.actions;

import org.eclipse.milo.opcua.stack.core.types.builtin.StatusCode;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import opcuaclientmx.impl.OpcUaClientWrite;

public class OpcUaWrite extends CustomJavaAction<java.lang.Void>
{
	/** @deprecated use OpcUaServerCfg.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __OpcUaServerCfg;
	private final opcuaclientmx.proxies.OpcUaServerCfg OpcUaServerCfg;
	private final java.lang.String NodeId;
	private final java.lang.String ValueToWrite;

	public OpcUaWrite(
		IContext context,
		IMendixObject _opcUaServerCfg,
		java.lang.String _nodeId,
		java.lang.String _valueToWrite
	)
	{
		super(context);
		this.__OpcUaServerCfg = _opcUaServerCfg;
		this.OpcUaServerCfg = _opcUaServerCfg == null ? null : opcuaclientmx.proxies.OpcUaServerCfg.initialize(getContext(), _opcUaServerCfg);
		this.NodeId = _nodeId;
		this.ValueToWrite = _valueToWrite;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		StatusCode response = new OpcUaClientWrite().writeData(this.ValueToWrite, this.OpcUaServerCfg, context(), this.NodeId);
		if( response != null ) { 
			if( response.isGood() )
				return null;
			else {
				String status = response.toString();
				String responseStr = "(none)";
				try { responseStr = response.toString(); } catch(Exception e) {}; //We don't care about this error, we want the response if it's there but doesn't matter if it's blank
			
				throw new CoreException(String.format("Error Writing to [Server:%s|NodeId:%s]; Status: \"%s;\" Response: \"%s\"",this.OpcUaServerCfg.getServerID(),this.NodeId,status,responseStr));
			}
		}
		else 
			throw new CoreException(String.format("Unable to send data to [Server:%s|NodeId:%s]",this.OpcUaServerCfg.getServerID(),this.NodeId));

			
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "OpcUaWrite";
	}

	// BEGIN EXTRA CODE
	


	// END EXTRA CODE
}
