// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package opcuaclientmx.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import opcuaclientmx.impl.OpcUaClientManager;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class OpcUaUpdateCachedServerSettings extends CustomJavaAction<java.lang.Void>
{
	/** @deprecated use ServerConfig.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __ServerConfig;
	private final opcuaclientmx.proxies.OpcUaServerCfg ServerConfig;

	public OpcUaUpdateCachedServerSettings(
		IContext context,
		IMendixObject _serverConfig
	)
	{
		super(context);
		this.__ServerConfig = _serverConfig;
		this.ServerConfig = _serverConfig == null ? null : opcuaclientmx.proxies.OpcUaServerCfg.initialize(getContext(), _serverConfig);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE

		OpcUaClientManager.updateConfigIfExists(getContext(), this.ServerConfig);

		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "OpcUaUpdateCachedServerSettings";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
