// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package opcuaclientmx.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import opcuaclientmx.impl.SubscriptionManager;

public class OpcUaSubscribe extends CustomJavaAction<IMendixObject>
{
	/** @deprecated use OpcUaServerCfg.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __OpcUaServerCfg;
	private final opcuaclientmx.proxies.OpcUaServerCfg OpcUaServerCfg;
	private final java.lang.String nodeId;
	private final java.lang.String OnMessageMicroflow;
	/** @deprecated use Subscription.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Subscription;
	private final opcuaclientmx.proxies.Subscription Subscription;

	public OpcUaSubscribe(
		IContext context,
		IMendixObject _opcUaServerCfg,
		java.lang.String _nodeId,
		java.lang.String _onMessageMicroflow,
		IMendixObject _subscription
	)
	{
		super(context);
		this.__OpcUaServerCfg = _opcUaServerCfg;
		this.OpcUaServerCfg = _opcUaServerCfg == null ? null : opcuaclientmx.proxies.OpcUaServerCfg.initialize(getContext(), _opcUaServerCfg);
		this.nodeId = _nodeId;
		this.OnMessageMicroflow = _onMessageMicroflow;
		this.__Subscription = _subscription;
		this.Subscription = _subscription == null ? null : opcuaclientmx.proxies.Subscription.initialize(getContext(), _subscription);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		return SubscriptionManager._getInstance().addSubscription(getContext(), this.OpcUaServerCfg, this.Subscription, this.nodeId, this.OnMessageMicroflow);
	
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "OpcUaSubscribe";
	}

	// BEGIN EXTRA CODE
	


	// END EXTRA CODE
}
