// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package opcuaclientmx.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the OpcUaClientMx module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aSu_ReinitializeSubscriptionsBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpcUaClientMx.ASu_ReinitializeSubscriptions");
		return builder;
	}

	public static boolean aSu_ReinitializeSubscriptions(IContext context)
	{
		Object result = aSu_ReinitializeSubscriptionsBuilder().execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder bSd_GracefullyShutdownSubscriptionsBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpcUaClientMx.BSd_GracefullyShutdownSubscriptions");
		return builder;
	}

	public static void bSd_GracefullyShutdownSubscriptions(IContext context)
	{
		bSd_GracefullyShutdownSubscriptionsBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mB_Create_OpcUaServerBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpcUaClientMx.MB_Create_OpcUaServer");
		return builder;
	}

	public static void mB_Create_OpcUaServer(IContext context)
	{
		mB_Create_OpcUaServerBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mB_DeleteSubscriptionBuilder(
		opcuaclientmx.proxies.MonitoredItem _monitoredItem,
		opcuaclientmx.proxies.OpcUaServerCfg _opcUaServerCfg
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpcUaClientMx.MB_DeleteSubscription");
		builder = builder.withParam("MonitoredItem", _monitoredItem);
		builder = builder.withParam("OpcUaServerCfg", _opcUaServerCfg);
		return builder;
	}

	public static void mB_DeleteSubscription(
		IContext context,
		opcuaclientmx.proxies.MonitoredItem _monitoredItem,
		opcuaclientmx.proxies.OpcUaServerCfg _opcUaServerCfg
	)
	{
		mB_DeleteSubscriptionBuilder(
				_monitoredItem,
				_opcUaServerCfg
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mB_OpcUaServerCfg_BrowseBuilder(
		opcuaclientmx.proxies.OpcUaServerCfg _opcUaServerCfg,
		opcuaclientmx.proxies.Troubleshooting _troubleshooting
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpcUaClientMx.MB_OpcUaServerCfg_Browse");
		builder = builder.withParam("OpcUaServerCfg", _opcUaServerCfg);
		builder = builder.withParam("Troubleshooting", _troubleshooting);
		return builder;
	}

	public static void mB_OpcUaServerCfg_Browse(
		IContext context,
		opcuaclientmx.proxies.OpcUaServerCfg _opcUaServerCfg,
		opcuaclientmx.proxies.Troubleshooting _troubleshooting
	)
	{
		mB_OpcUaServerCfg_BrowseBuilder(
				_opcUaServerCfg,
				_troubleshooting
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mB_OpcUaServerCfg_GetDisplayNameBuilder(
		opcuaclientmx.proxies.Troubleshooting _troubleshooting,
		opcuaclientmx.proxies.OpcUaServerCfg _opcUaServerCfg
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpcUaClientMx.MB_OpcUaServerCfg_GetDisplayName");
		builder = builder.withParam("Troubleshooting", _troubleshooting);
		builder = builder.withParam("OpcUaServerCfg", _opcUaServerCfg);
		return builder;
	}

	public static void mB_OpcUaServerCfg_GetDisplayName(
		IContext context,
		opcuaclientmx.proxies.Troubleshooting _troubleshooting,
		opcuaclientmx.proxies.OpcUaServerCfg _opcUaServerCfg
	)
	{
		mB_OpcUaServerCfg_GetDisplayNameBuilder(
				_troubleshooting,
				_opcUaServerCfg
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mB_OpcUaServerCfg_MethodBuilder(
		opcuaclientmx.proxies.Troubleshooting _troubleshooting,
		opcuaclientmx.proxies.OpcUaServerCfg _opcUaServerCfg
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpcUaClientMx.MB_OpcUaServerCfg_Method");
		builder = builder.withParam("Troubleshooting", _troubleshooting);
		builder = builder.withParam("OpcUaServerCfg", _opcUaServerCfg);
		return builder;
	}

	public static void mB_OpcUaServerCfg_Method(
		IContext context,
		opcuaclientmx.proxies.Troubleshooting _troubleshooting,
		opcuaclientmx.proxies.OpcUaServerCfg _opcUaServerCfg
	)
	{
		mB_OpcUaServerCfg_MethodBuilder(
				_troubleshooting,
				_opcUaServerCfg
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mB_OpcUaServerCfg_ReadBuilder(
		opcuaclientmx.proxies.OpcUaServerCfg _opcUaServerCfg,
		opcuaclientmx.proxies.Troubleshooting _troubleshooting
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpcUaClientMx.MB_OpcUaServerCfg_Read");
		builder = builder.withParam("OpcUaServerCfg", _opcUaServerCfg);
		builder = builder.withParam("Troubleshooting", _troubleshooting);
		return builder;
	}

	public static void mB_OpcUaServerCfg_Read(
		IContext context,
		opcuaclientmx.proxies.OpcUaServerCfg _opcUaServerCfg,
		opcuaclientmx.proxies.Troubleshooting _troubleshooting
	)
	{
		mB_OpcUaServerCfg_ReadBuilder(
				_opcUaServerCfg,
				_troubleshooting
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mB_OpcUaServerCfg_Subscribe_simpleBuilder(
		opcuaclientmx.proxies.OpcUaServerCfg _opcUaServer,
		opcuaclientmx.proxies.Troubleshooting _troubleshooting
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpcUaClientMx.MB_OpcUaServerCfg_Subscribe_simple");
		builder = builder.withParam("OpcUaServer", _opcUaServer);
		builder = builder.withParam("Troubleshooting", _troubleshooting);
		return builder;
	}

	public static void mB_OpcUaServerCfg_Subscribe_simple(
		IContext context,
		opcuaclientmx.proxies.OpcUaServerCfg _opcUaServer,
		opcuaclientmx.proxies.Troubleshooting _troubleshooting
	)
	{
		mB_OpcUaServerCfg_Subscribe_simpleBuilder(
				_opcUaServer,
				_troubleshooting
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mB_OpcUaServerCfg_Subscribe_wMsgBuilder(
		opcuaclientmx.proxies.OpcUaServerCfg _opcUaServer,
		opcuaclientmx.proxies.Troubleshooting _troubleshooting
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpcUaClientMx.MB_OpcUaServerCfg_Subscribe_wMsg");
		builder = builder.withParam("OpcUaServer", _opcUaServer);
		builder = builder.withParam("Troubleshooting", _troubleshooting);
		return builder;
	}

	public static void mB_OpcUaServerCfg_Subscribe_wMsg(
		IContext context,
		opcuaclientmx.proxies.OpcUaServerCfg _opcUaServer,
		opcuaclientmx.proxies.Troubleshooting _troubleshooting
	)
	{
		mB_OpcUaServerCfg_Subscribe_wMsgBuilder(
				_opcUaServer,
				_troubleshooting
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mB_OpcUaServerCfg_WriteBuilder(
		opcuaclientmx.proxies.OpcUaServerCfg _opcUaServer,
		opcuaclientmx.proxies.Troubleshooting _troubleshooting
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpcUaClientMx.MB_OpcUaServerCfg_Write");
		builder = builder.withParam("OpcUaServer", _opcUaServer);
		builder = builder.withParam("Troubleshooting", _troubleshooting);
		return builder;
	}

	public static void mB_OpcUaServerCfg_Write(
		IContext context,
		opcuaclientmx.proxies.OpcUaServerCfg _opcUaServer,
		opcuaclientmx.proxies.Troubleshooting _troubleshooting
	)
	{
		mB_OpcUaServerCfg_WriteBuilder(
				_opcUaServer,
				_troubleshooting
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mB_ReconnectExistingSubscriptionsBuilder(
		opcuaclientmx.proxies.OpcUaServerCfg _opcUaServer
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpcUaClientMx.MB_ReconnectExistingSubscriptions");
		builder = builder.withParam("OpcUaServer", _opcUaServer);
		return builder;
	}

	public static void mB_ReconnectExistingSubscriptions(
		IContext context,
		opcuaclientmx.proxies.OpcUaServerCfg _opcUaServer
	)
	{
		mB_ReconnectExistingSubscriptionsBuilder(
				_opcUaServer
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mB_Save_OpcUaServerBuilder(
		opcuaclientmx.proxies.OpcUaServerCfg _opcUaServer
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpcUaClientMx.MB_Save_OpcUaServer");
		builder = builder.withParam("OpcUaServer", _opcUaServer);
		return builder;
	}

	public static void mB_Save_OpcUaServer(
		IContext context,
		opcuaclientmx.proxies.OpcUaServerCfg _opcUaServer
	)
	{
		mB_Save_OpcUaServerBuilder(
				_opcUaServer
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mB_ShowAdvancedTroubleshootingBuilder(
		opcuaclientmx.proxies.OpcUaServerCfg _opcUaServerCfg
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpcUaClientMx.MB_ShowAdvancedTroubleshooting");
		builder = builder.withParam("OpcUaServerCfg", _opcUaServerCfg);
		return builder;
	}

	public static void mB_ShowAdvancedTroubleshooting(
		IContext context,
		opcuaclientmx.proxies.OpcUaServerCfg _opcUaServerCfg
	)
	{
		mB_ShowAdvancedTroubleshootingBuilder(
				_opcUaServerCfg
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mB_Subscription_RefreshBuilder(
		opcuaclientmx.proxies.MonitoredItem _monitoredItem,
		opcuaclientmx.proxies.OpcUaServerCfg _opcUaServerCfg
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpcUaClientMx.MB_Subscription_Refresh");
		builder = builder.withParam("MonitoredItem", _monitoredItem);
		builder = builder.withParam("OpcUaServerCfg", _opcUaServerCfg);
		return builder;
	}

	public static void mB_Subscription_Refresh(
		IContext context,
		opcuaclientmx.proxies.MonitoredItem _monitoredItem,
		opcuaclientmx.proxies.OpcUaServerCfg _opcUaServerCfg
	)
	{
		mB_Subscription_RefreshBuilder(
				_monitoredItem,
				_opcUaServerCfg
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mB_Subscription_UnsubscribeBuilder(
		opcuaclientmx.proxies.MonitoredItem _subscription,
		opcuaclientmx.proxies.OpcUaServerCfg _opcUaServerCfg
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpcUaClientMx.MB_Subscription_Unsubscribe");
		builder = builder.withParam("Subscription", _subscription);
		builder = builder.withParam("OpcUaServerCfg", _opcUaServerCfg);
		return builder;
	}

	public static void mB_Subscription_Unsubscribe(
		IContext context,
		opcuaclientmx.proxies.MonitoredItem _subscription,
		opcuaclientmx.proxies.OpcUaServerCfg _opcUaServerCfg
	)
	{
		mB_Subscription_UnsubscribeBuilder(
				_subscription,
				_opcUaServerCfg
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mB_TestConnectionOPCServerBuilder(
		opcuaclientmx.proxies.OpcUaServerCfg _opcUaServerCfg
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpcUaClientMx.MB_TestConnectionOPCServer");
		builder = builder.withParam("OpcUaServerCfg", _opcUaServerCfg);
		return builder;
	}

	public static void mB_TestConnectionOPCServer(
		IContext context,
		opcuaclientmx.proxies.OpcUaServerCfg _opcUaServerCfg
	)
	{
		mB_TestConnectionOPCServerBuilder(
				_opcUaServerCfg
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder reinitialzeSubscriptionBuilder(
		opcuaclientmx.proxies.MonitoredItem _iteratorSubscription
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpcUaClientMx.ReinitialzeSubscription");
		builder = builder.withParam("IteratorSubscription", _iteratorSubscription);
		return builder;
	}

	public static void reinitialzeSubscription(
		IContext context,
		opcuaclientmx.proxies.MonitoredItem _iteratorSubscription
	)
	{
		reinitialzeSubscriptionBuilder(
				_iteratorSubscription
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder save_OpcUaServerBuilder(
		opcuaclientmx.proxies.OpcUaServerCfg _opcUaServer
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpcUaClientMx.Save_OpcUaServer");
		builder = builder.withParam("OpcUaServer", _opcUaServer);
		return builder;
	}

	public static boolean save_OpcUaServer(
		IContext context,
		opcuaclientmx.proxies.OpcUaServerCfg _opcUaServer
	)
	{
		Object result = save_OpcUaServerBuilder(
				_opcUaServer
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder subscriptionIncomingData_Process_TESTBuilder(
		java.lang.String _payload,
		java.lang.String _subscriptionID,
		java.lang.String _monitoredItemID
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpcUaClientMx.SubscriptionIncomingData_Process_TEST");
		builder = builder.withParam("Payload", _payload);
		builder = builder.withParam("SubscriptionID", _subscriptionID);
		builder = builder.withParam("MonitoredItemID", _monitoredItemID);
		return builder;
	}

	public static void subscriptionIncomingData_Process_TEST(
		IContext context,
		java.lang.String _payload,
		java.lang.String _subscriptionID,
		java.lang.String _monitoredItemID
	)
	{
		subscriptionIncomingData_Process_TESTBuilder(
				_payload,
				_subscriptionID,
				_monitoredItemID
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder subscriptionIncomingData_Process_wMessage_TESTBuilder(
		opcuaclientmx.proxies.Message _message
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpcUaClientMx.SubscriptionIncomingData_Process_wMessage_TEST");
		builder = builder.withParam("Message", _message);
		return builder;
	}

	public static void subscriptionIncomingData_Process_wMessage_TEST(
		IContext context,
		opcuaclientmx.proxies.Message _message
	)
	{
		subscriptionIncomingData_Process_wMessage_TESTBuilder(
				_message
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder unsubscribeSubscriptionBuilder(
		opcuaclientmx.proxies.MonitoredItem _iteratorSubscription,
		boolean _restartSubscriptionOnNextReboot
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpcUaClientMx.UnsubscribeSubscription");
		builder = builder.withParam("IteratorSubscription", _iteratorSubscription);
		builder = builder.withParam("RestartSubscriptionOnNextReboot", _restartSubscriptionOnNextReboot);
		return builder;
	}

	public static void unsubscribeSubscription(
		IContext context,
		opcuaclientmx.proxies.MonitoredItem _iteratorSubscription,
		boolean _restartSubscriptionOnNextReboot
	)
	{
		unsubscribeSubscriptionBuilder(
				_iteratorSubscription,
				_restartSubscriptionOnNextReboot
			)
			.execute(context);
	}
}
